name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node v14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Install packages
        run: |
          yarn install
      - name: Run linter
        run: |
          yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node v14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Install packages
        run: |
          yarn install
      - name: Extract test 
        run: |
          yarn extract-test-data
      - name: Run tests
        rune: |
          yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node v14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Install packages
        run: |
          yarn install
      - name: Build package
        run: |
          yarn build